<!DOCTYPE html>
<html lang="fr"><head><meta charset="utf-8"><title>Primes chauffeurs</title>
<style>
@page{size:A4 landscape;margin:12mm 9mm 14mm}*{box-sizing:border-box}body{margin:0;color:#111827;font-family:DejaVu Sans,sans-serif;font-size:7px;line-height:1.3}.header{position:relative;padding:7mm 7mm 5mm;margin-bottom:5mm;background:#111827;color:#fff;border-radius:5mm;overflow:hidden}.header:before{content:"";position:absolute;left:0;top:0;bottom:0;width:6px;background:#c1121f}.header-table{width:100%;border-collapse:collapse}.logo{width:92px}.brand{font-size:20px;font-weight:900}.brand span{color:#ef4444}.title{text-align:right}.title h1{margin:0;font-size:22px;text-transform:uppercase;letter-spacing:.04em}.title p{margin:4px 0 0;color:#cbd5e1;font-size:7px;text-transform:uppercase;letter-spacing:.18em;font-weight:900}.meta{width:100%;margin-bottom:5mm;border-collapse:separate;border-spacing:2mm 0}.meta td{padding:3mm;border:1px solid #e2e8f0;border-radius:3mm;background:#f8fafc}.label{display:block;margin-bottom:2px;color:#94a3b8;font-size:5.8px;text-transform:uppercase;letter-spacing:.1em;font-weight:900}.value{font-size:8px;font-weight:900}.value.red{color:#991b1f}.driver-section{margin-bottom:5mm;page-break-inside:auto}.driver-section+.driver-section{page-break-before:auto}.driver-heading{page-break-after:avoid;margin-bottom:2mm;padding:2.5mm 3mm;color:#fff;background:linear-gradient(90deg,#991b1f,#111827);border-radius:2.5mm}.driver-heading table{width:100%;border-collapse:collapse}.driver-name{font-size:10px;font-weight:900;text-transform:uppercase}.driver-totals{text-align:right;color:#e2e8f0;font-size:6.5px;font-weight:800}.lines{width:100%;border-collapse:collapse;table-layout:fixed}.lines thead{display:table-header-group}.lines tr{page-break-inside:avoid}.lines th{padding:2mm 1.3mm;color:#fff;background:#1e293b;text-align:left;font-size:5.8px;text-transform:uppercase;letter-spacing:.04em}.lines td{padding:2mm 1.3mm;border-bottom:1px solid #e2e8f0;vertical-align:top;word-wrap:break-word}.lines tbody tr:nth-child(even) td{background:#f8fafc}.date{width:7%}.time{width:5%}.ref{width:8%}.service{width:11%}.type{width:9%}.route{width:16%}.vehicle{width:11%}.pax{width:4%;text-align:center}.clients{width:11%}.supplier{width:11%}.guide{width:7%}.section-total td{padding:2.5mm;color:#991b1f;background:#fff1f2!important;font-weight:900;border-top:1px solid #fecdd3}.empty{padding:15mm;text-align:center;color:#64748b;font-size:10px}.footer-note{margin-top:4mm;color:#94a3b8;font-size:6px;text-align:center}
</style></head><body>
@php $period = \Carbon\Carbon::parse($filters['date_from'])->format('d/m/Y').' — '.\Carbon\Carbon::parse($filters['date_to'])->format('d/m/Y'); @endphp
<header class="header"><table class="header-table"><tr><td>@if($logoDataUri)<img class="logo" src="{{ $logoDataUri }}" alt="MD Tours">@else<div class="brand"><span>MD</span> TOURS</div>@endif</td><td class="title"><h1>Relevé des primes chauffeurs</h1><p>Rapport des prestations par chauffeur</p></td></tr></table></header>
<table class="meta"><tr>
<td style="width:32%"><span class="label">Période</span><span class="value">{{ $period }}</span></td>
<td style="width:38%"><span class="label">Types de service</span><span class="value red">{{ $typeServices->join(' · ') }}</span></td>
<td style="width:10%"><span class="label">Chauffeurs</span><span class="value">{{ $summary['drivers_count'] }}</span></td>
<td style="width:10%"><span class="label">Prestations</span><span class="value">{{ $summary['count'] }}</span></td>
<td style="width:10%"><span class="label">Généré le</span><span class="value">{{ $generatedAt->format('d/m/Y H:i') }}</span></td>
</tr></table>
@forelse($groups as $group)
<section class="driver-section"><div class="driver-heading"><table><tr><td class="driver-name">Chauffeur : {{ $group['driver'] }}</td><td class="driver-totals">{{ $group['days'] }} jour(s) · {{ $group['references'] }} dossier(s) · {{ $group['services'] }} prestation(s)</td></tr></table></div>
<table class="lines"><thead><tr><th class="date">Date</th><th class="time">Heure</th><th class="ref">Référence</th><th class="service">Service</th><th class="type">Type</th><th class="route">Trajet</th><th class="vehicle">Véhicule</th><th class="pax">PAX</th><th class="clients">Clients</th><th class="supplier">Fournisseur</th><th class="guide">Guide</th></tr></thead><tbody>
@foreach($group['rows'] as $row)<tr><td>{{ $row['date'] }}</td><td>{{ $row['time'] }}</td><td><strong>{{ $row['reference'] }}</strong></td><td>{{ $row['service'] }}</td><td>{{ $row['service_type'] }}</td><td>{{ $row['start_point'] }} → {{ $row['destination'] }}</td><td>{{ $row['vehicle'] }}</td><td class="pax">{{ $row['pax'] }}</td><td>{{ count($row['clients']) ? implode(', ', $row['clients']) : '-' }}</td><td>{{ $row['supplier_vehicle'] }}<br>{{ $row['supplier_client'] }}</td><td>{{ $row['guide'] }}</td></tr>@endforeach
<tr class="section-total"><td colspan="11">Sous-total {{ $group['driver'] }} : {{ $group['days'] }} jour(s), {{ $group['references'] }} dossier(s), {{ $group['services'] }} prestation(s)</td></tr>
</tbody></table></section>
@empty<div class="empty">Aucune prestation ne correspond aux filtres sélectionnés.</div>@endforelse
<div class="footer-note">Document de consultation généré par MD Tours — aucune donnée financière, facture ou paiement n’a été modifié.</div>
<script type="text/php">
if (isset($pdf)) { $pdf->page_text(735, 565, "Page {PAGE_NUM} / {PAGE_COUNT}", null, 7, [0.39, 0.45, 0.55]); }
</script>
</body></html>
