<script setup>
import { Link } from '@inertiajs/vue3';
const props=defineProps({planning:Object});
const date=v=>v?String(v).slice(0,10):'--';
const clients=()=>{const rows=props.planning.planning_clients||[];return rows.map(x=>x.client?.full_name).filter(Boolean)};
const destination=()=>props.planning.destination?.city||props.planning.destination?.name||'Non renseignée';
</script>
<template><article class="planning-card">
 <div class="head"><div class="date"><b>{{date(planning.date_du).slice(8,10)}}</b><span>{{date(planning.date_du).slice(5,7)}}/{{date(planning.date_du).slice(0,4)}}</span></div><div class="identity"><strong>{{planning.ref_dossier||'Sans référence'}}</strong><span>{{planning.service?.designation||'Service non renseigné'}}</span></div><span class="badge">{{planning.type_service||planning.service?.type||'Service'}}</span></div>
 <div class="clients"><span class="material-icons-outlined">group</span><div><small>{{clients().length>1?'Clients':'Client'}}</small><b v-for="name in clients()" :key="name">{{name}}</b><b v-if="!clients().length">Client non renseigné</b></div></div>
 <div class="route"><div><small>Départ</small><b>{{planning.point_depart||'Non renseigné'}}</b></div><span class="material-icons-outlined">trending_flat</span><div><small>Destination</small><b>{{destination()}}</b></div></div>
 <div class="meta"><span><i class="material-icons-outlined">schedule</i>{{String(planning.heure||'--:--').slice(0,5)}}</span><span><i class="material-icons-outlined">people</i>{{planning.nbr_personnes||0}} pax</span><span><i class="material-icons-outlined">directions_car</i>{{planning.vehicule?.matricule||planning.supplier_vehicule?.name||'--'}}</span></div>
 <Link :href="route('driver.plannings.show',planning.id)" class="open">Ouvrir le dossier<span class="material-icons-outlined">arrow_forward</span></Link>
</article></template>
<style scoped>.planning-card{padding:15px;border:1px solid #e2e8f0;border-radius:22px;background:#fff;box-shadow:0 8px 26px #0f172a0b;min-width:0}.head{display:flex;align-items:center;gap:10px}.date{width:50px;min-height:58px;border:1px solid #fecaca;border-radius:15px;background:#fef2f2;display:grid;place-content:center;text-align:center;color:#991b1b}.date b{font-size:18px}.date span{font-size:9px;font-weight:900}.identity{flex:1;min-width:0}.identity strong,.identity span{display:block}.identity strong{font-size:14px}.identity span{margin-top:3px;color:#64748b;font-size:11px;font-weight:800}.badge{max-width:30%;padding:6px 9px;border-radius:99px;background:#ede9fe;color:#6d28d9;font-size:9px;font-weight:900}.clients{margin-top:10px;display:flex;gap:7px;color:#991b1b}.clients small,.clients b{display:block}.clients small{color:#94a3b8;font-size:9px;text-transform:uppercase}.clients b{color:#334155;font-size:11px;line-height:16px}.route{margin-top:10px;padding:10px;border-radius:14px;background:#f8fafc;display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);align-items:center;gap:8px}.route small,.route b{display:block}.route small{color:#94a3b8;font-size:9px;font-weight:900}.route b{margin-top:2px;color:#334155;font-size:10px;overflow-wrap:anywhere}.route>.material-icons-outlined{color:#cbd5e1}.meta{margin-top:9px;display:flex;flex-wrap:wrap;gap:6px}.meta span{padding:5px 7px;border-radius:9px;background:#f1f5f9;color:#64748b;display:flex;align-items:center;gap:4px;font-size:9px;font-weight:800}.meta i{font-size:14px}.open{margin-top:11px;color:#dc2626;display:flex;align-items:center;justify-content:flex-end;gap:5px;font-size:11px;font-weight:900;text-decoration:none}.open span{font-size:15px}@media(max-width:420px){.planning-card{padding:12px;border-radius:18px}.badge{display:none}}</style>
