name: Deploy Lghzaoui

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e

            echo "==== STEP 1: Set remote URL ===="
            cd /srv/apps/NorgrainsLghzaoui/repo
            git remote set-url origin git@github.com:JB30061997/ProductionLaghzaoui.git
            git remote -v

            echo "==== STEP 2: Test SSH ===="
            ssh -T git@github.com || true

            echo "==== STEP 3: Reset and Pull ===="
            git reset --hard
            git pull origin main

            echo "==== STEP 4: Restart docker ===="
            cd ../docker
            docker compose down
            docker compose up -d --build
